config/routes.rb
Rails.application.routes.draw do

  resources :refeicos, :users, :appointments

  root "home#index"

  get 'sessions/new'

  get 'users/new'

  get "home/about"

  get "home/FAQ"

  get "home/Services"

  get "home/Payment"

  get "home/Terms"

  get "home/Privacy"

  get    'sign_in'   => 'sessions#new'

  post   'sign_in'   => 'sessions#create'

  get 'sign_out', to: 'sessions#destroy', as: :sign_out

  get 'dashboard', to: 'dashboards#show'

  get 'bmi_calculator', to: 'dashboards#bmi_calculator'

  get 'calculate_bmi', to: 'dashboards#calculate_bmi'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/refeico.rb
class Refeico < ApplicationRecord
  validates :refeicao, presence: { message: "não é permitido campo vazio" }
  validates :data, presence: { message: "não é permitido campo vazio" }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true, length: { maximum: 50 }
  validates :password, presence: true, length: { minimum: 6 }
  VALID_EMAIL_FORMAT = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email, presence: true, length: { maximum: 260 }, format: { with: VALID_EMAIL_FORMAT }, uniqueness: { case_sensitive: false }

  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  helper_method :current_user, :user_signed_in?

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !current_user.nil?
  end

  def block_access
    redirect_to dashboard_path if user_signed_in?
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def index
    @appointments = Appointment.all
  end

  def show
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      redirect_to @appointment, notice: 'Agendamento foi criado.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment, notice: 'Agendamento foi editado.'
    else
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_url, notice: 'Agendamento foi deletado.'
  end

  private

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:date, :hour, :doctor)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  end

  def bmi_calculator
  end

  def calculate_bmi
  end

  def show
    @next_appointment = Appointment.where('date >= ?', Date.today).order(:date, :hour).first
    @last_meal = Refeico.last
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  def FAQ
  end
  def Payment
  end
end

app/controllers/refeicos_controller.rb
class RefeicosController < ApplicationController
  before_action :set_refeico, only: %i[ show edit update destroy ]

  def index
    @refeicos = Refeico.all
  end

  def show
  end

  def new
    @refeico = Refeico.new
  end

  def edit
  end

  def create
    @refeico = Refeico.new(refeico_params)

    respond_to do |format|
      if @refeico.save
        format.html { redirect_to refeico_url(@refeico), notice: "Refeição foi criada com sucesso." }
        format.json { render :show, status: :created, location: @refeico }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @refeico.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @refeico.update(refeico_params)
        format.html { redirect_to refeico_url(@refeico), notice: "Refeição foi atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @refeico }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @refeico.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @refeico.destroy

    respond_to do |format|
      format.html { redirect_to refeicos_url, notice: "Refeição foi deletada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    def set_refeico
      @refeico = Refeico.find(params[:id])
    end

    def refeico_params
      params.require(:refeico).permit(:refeicao, :data, :descricao, :calorias)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  before_action :block_access, only: [:new, :create]

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to dashboard_path, notice: 'Entrou na conta!'
    else
      flash.now[:danger] = 'email ou senha inválidos'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_url, notice: "Saiu da conta!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "Usuário foi criado com sucesso!"
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      logger.debug @user.errors.full_messages.to_sentence
      render action: :new
    end
  end

  def show
    @user = User.find(params[:id])
  end



  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
    when :notice then "info"
    when :success then "success"
    when :error then "danger"
    when :alert then "warning"
    else flash_type.to_s
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/refeicos_helper.rb
module RefeicosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in
              session[:user_id] = @user.id
  end
  def current_user
              @current_user ||= User.find_by(id: session[:user_id])
  end
  def block_access
              if current_user.present?
                         redirect_to users_path
              end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_form.html.erb
<!-- app/views/appointments/_form.html.erb -->

<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> Impediram que esse agendamento fosse salvo:</h2>

      <ul>
        <% appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Data %>
    <%= form.date_field :date %>
  </div>

  <div class="field">
    <%= form.label :Hora %>
    <%= form.time_field :hour %>
  </div>

  <div class="field">
    <%= form.label :Nutricionista %>
    <%= form.text_field :doctor %>
  </div>

  <div class="actions">
  <%= form.submit (@appointment.new_record? ? 'Criar Agendamento' : 'Atualizar Agendamento') %>
  </div>

<% end %>

app/views/appointments/edit.html.erb
<!-- app/views/appointments/edit.html.erb -->

<h1>Editar Agendamentos</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Mostrar', @appointment %> |
<%= link_to 'Voltar Para Agendamento', appointments_path %>

app/views/appointments/index.html.erb
<!-- app/views/appointments/index.html.erb -->

<p id="notice"><%= notice %></p>

<h1>Agendamentos</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Hora</th>
      <th>Nutricionista</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date.strftime("%d-%m-%Y") %></td>
        <td><%= appointment.hour.strftime("%H:%M") %></td>
        <td><%= appointment.doctor %></td>
        <td><%= link_to 'Mostrar', appointment, class: 'link-button' %></td>
        <td><%= link_to 'Editar', edit_appointment_path(appointment), class: 'link-button' %></td>
        <td><%= button_to 'Destruir', appointment, method: :delete, data: { confirm: 'Você tem certeza?' }, form: { class: 'inline' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Agendamento', new_appointment_path %>
<%= link_to 'Voltar Para Dashboard', dashboard_path %>

app/views/appointments/new.html.erb
<%= form_with(model: @appointment, local: true) do |form| %>
  <div class="field">
    <%= form.label :Data %>
    <%= form.date_field :date %>
  </div>
  <div class="field">
    <%= form.label :Hora %>
    <%= form.time_field :hour %>
  </div>
  <div class="field">
    <%= form.label :Nutricionista %>
    <%= form.text_field :doctor %>
  </div>
  <div class="actions">
  <%= form.submit (@appointment.new_record? ? 'Criar Agendamento' : 'Atualizar Agendamento') %>
  </div>
  <%= link_to 'Voltar', appointments_path %>
<% end %>

app/views/appointments/show.html.erb
<!-- app/views/appointments/show.html.erb -->

<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @appointment.date.strftime("%d-%m-%Y") %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @appointment.hour.strftime("%H:%M") %>
</p>

<p>
  <strong>Nutricionista:</strong>
  <%= @appointment.doctor %>
</p>

<%= link_to 'Editar', edit_appointment_path(@appointment) %> |
<%= link_to 'Voltar Para Agendamento', appointments_path %>

app/views/dashboards/bmi_calculator.html.erb
<div class="bmi-calculator">
  <h1>Calculadora de IMC</h1>
  <%= form_with(id: "bmi-form", local: false) do |form| %>
    <div class="field">
      <%= label_tag :height, "Altura (em metros)" %>
      <%= number_field_tag :height, nil, step: 0.01, required: true, id: "height-input" %>
    </div>
    <div class="field">
      <%= label_tag :weight, "Peso (em quilogramas)" %>
      <%= number_field_tag :weight, nil, step: 0.1, required: true, id: "weight-input" %>
    </div>
    <%= button_tag(type: 'button', id: 'calculate-bmi', class: 'button') do %>
      Calcular IMC
    <% end %>
    <div id="bmi-result"></div>
  <% end %>

  <%= link_to 'Voltar', dashboard_path %>
</div>

app/views/dashboards/show.html.erb
<!-- app/views/dashboards/show.html.erb -->
<div class="dashboard">
  <!-- Navigation Bar -->
  <nav class="navbar">
    <!-- Links to different sections -->
    <div class="navbar-menu">
      <%= link_to 'Calculadora de IMC', bmi_calculator_path, id: 'open-bmi-calculator' %>
      <a href="/appointments">Agendar Nutricionista</a>
      <a href="/refeicos">Anotar Refeições</a>
    </div>
  </nav>

  <!-- Main Area -->
  <div class="main-area">
  <div class="greeting-card">
  <% if user_signed_in? %>
    <h2>Bem vindo, <%= current_user.name.capitalize %>!</h2>
  <% else %>
    <h2>Bem vindo!</h2>
  <% end %>
    <p>Aqui está o seu resumo de saúde para hoje:</p>
  </div>

    <div class="stats-grid">
      <div class="card water-intake">
        <h3>Ingestão de Água</h3>
        <progress id="water-progress" value="0" max="10"></progress>
        <p id="water-text">0 de 10 copos</p>
      </div>

      <div class="card step-count">
        <h3>Contagem de passos</h3>
        <p id="step-count">0 passos</p>
      </div>

      <div class="card next-appointment">
        <h3>Próxima agenda</h3>
        <% if @next_appointment %>
          <p>
            <%= l(@next_appointment.date, format: :long) %>,
            <%= @next_appointment.hour.strftime("%H:%M") %> com Dr. <%= @next_appointment.doctor %>
          </p>
        <% else %>
          <p>Sem agendamentos</p>
        <% end %>
      </div>
    </div>

    <div class="card last-meal">
      <h3>Última Refeição</h3>
      <% if @last_meal %>
        <p><strong>Nome:</strong> <%= @last_meal.refeicao %></p>
        <p><strong>Data:</strong> <%= @last_meal.data.strftime("%d/%m/%Y") %></p>
        <p><strong>Descrição:</strong> <%= @last_meal.descricao %></p>
        <p><strong>Calorias:</strong> <%= @last_meal.calorias %></p>
      <% else %>
        <p>Sem última refeição</p>
      <% end %>
    </div>

    <div class="action-buttons">
      <%= button_tag 'Adicionar Copo', type: 'button', id: 'add-water', class: 'button-style', onclick: 'incrementWaterIntake()' %>
      <%= button_tag 'Adicionar Passos', type: 'button', id: 'add-steps', class: 'button-style', onclick: 'incrementStepCount()' %>
    </div>

    <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', (event) => {
        document.getElementById('step-count').textContent = '0 passos';
      });
    </script>
</div>

app/views/home/FAQ.html.erb
<!--Section: FAQ-->
<section class="text-box">
  <h3 class="text-center mb-4 pb-2 text-dark fw-bold">Perguntas Frequentes</h3>
  <p class="text-center mb-5">
    Encontre as respostas para as perguntas mais frequentes na sessão abaixo
  </p>
  <div class="row">
    <div class="col-md-6 col-lg-4 mb-4">
      <h6 class="mb-3 text-dark"><i class="far fa-paper-plane text-dark pe-2"></i> Qual o intuito do site?</h6>
      <p>
        <strong><u>Saúde!</u></strong> Criamos o site para ajudar as pessoas a manter um controle sobre a sua alimentação,
        pontuando as refeições diárias, calorias e dias da semana.
      </p>
    </div>
<div class="col-md-6 col-lg-4 mb-4">
  <h6 class="mb-3 text-dark"><i class="fas fa-pen-alt text-dark pe-2"></i> O site é cobrado? </h6>
  <p>
    <strong><u>Sim, somos freemium!</u></strong> Temos sistema de freemium, ou seja, você pode optar por uma funcionalidade gratuita e por uma
    funcionalidade com opções mais personalidades onde existe uma pequena cobrança.
  </p>
</div>

<div class="col-md-6 col-lg-4 mb-4">
  <h6 class="mb-3 text-dark"><i class="fas fa-user text-dark pe-2"></i> Existe um plano anual?</h6>
  <p>
  <strong><u>Atualmente</u></strong>, oferecemos apenas assinatura mensal. Você pode atualizar ou cancelar sua conta mensal a qualquer momento, sem nenhuma obrigação adicional.
  </p>
</div>

<div class="col-md-6 col-lg-4 mb-4">
  <h6 class="mb-3 text-dark"><i class="fas fa-rocket text-dark pe-2"></i> Posso trocar de forma de pagamento?</h6>
  <p>
  <strong><u>Sim</u></strong>. Acesse a seção de cobrança do seu painel e atualize suas informações de pagamento.
  </p>
</div>

<div class="col-md-6 col-lg-4 mb-4">
  <h6 class="mb-3 text-dark"><i class="fas fa-home text-dark pe-2"></i> Posso pedir reembolso?</h6>
  <p><strong><u>Infelizmente não</u>.</strong> Não emitimos reembolsos totais ou parciais por qualquer motivo.</p>
</div>

<div class="col-md-6 col-lg-4 mb-4">
  <h6 class="mb-3 text-dark"><i class="fas fa-book-open text-dark pe-2"></i> Existe degustação do sistema?</h6>
  <p>
    Claro! Ficamos felizes em oferecer um plano gratuito para qualquer pessoa que queira experimentar nosso serviço.
  </p>
</div>
  </div>
</section>
<!--Section: FAQ-->

app/views/home/Payment.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img src="https://mdbcdn.b-cdn.net/img/Photos/Vertical/mountain1.webp"
                alt="login form" class="img-fluid" />
    </div>
    <div class="col-md-6">
      <div class="text-box">
        <h2>Opções de Pagamento</h2>
        <p>
        <ul style="font-size: 14px;">
        <li>Na versão Freemium do nosso serviço, você não precisa se preocupar com cobranças. É totalmente gratuito! Além disso, temos uma oferta especial para você: experimente a versão Premium gratuitamente por 30 dias. Assim, você poderá desfrutar de todos os recursos extras que oferecemos.</li>
        <li>E se você decidir continuar com a versão Premium, oferecemos uma assinatura mensal por apenas R$20. É uma ótima oportunidade de ter acesso a recomendações personalizadas, monitoramento avançado de calorias e programas de treinamento exclusivos.</li>
        <li>E não se preocupe com a forma de pagamento. Aceitamos débito bancário, cartão de crédito, débito e até mesmo Pix. Queremos tornar a experiência o mais conveniente possível para você.</li>
        <li>Então, aproveite a oferta de degustação gratuita da versão Premium por 30 dias e descubra como podemos ajudar você a alcançar seus objetivos de saúde e bem-estar. Não perca essa oportunidade!</li>
        </p>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/home/Privacy.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="text-box">
        <h2>Política de Privacidade do MealTracker</h2>
        <p>Sua privacidade é importante para nós. Esta Política de Privacidade descreve como suas informações pessoais são coletadas, usadas e compartilhadas ao usar o MealTracker. Ao acessar ou utilizar o MealTracker, você concorda com esta política.</p>

        <h5>Informações Coletadas</h5>
        <p>Coletamos informações que você nos fornece diretamente, como nome, endereço de e-mail, e informações sobre suas refeições e saúde. Também podemos coletar informações automaticamente, como logs de acesso e cookies.</p>

        <h5>Uso das Informações</h5>
        <p>Usamos suas informações para fornecer, manter, proteger e melhorar nossos serviços. Isso inclui personalizar conteúdo, entender o uso dos serviços e comunicar-se com você sobre sua conta.</p>

        <h5>Compartilhamento de Informações</h5>
        <p>Não compartilhamos suas informações pessoais com terceiros, exceto quando necessário para operar, manter ou melhorar nossos serviços. Podemos compartilhar informações não pessoais ou agregadas publicamente.</p>

        <h5>Segurança</h5>
        <p>Tomamos medidas para proteger suas informações pessoais, mas lembre-se de que nenhum método de transmissão pela Internet ou armazenamento eletrônico é 100% seguro.</p>

        <h5>Seus Direitos</h5>
        <p>Você tem o direito de acessar, corrigir ou excluir suas informações pessoais. Entre em contato conosco para exercer esses direitos.</p>

        <h5>Alterações na Política de Privacidade</h5>
        <p>Podemos atualizar esta Política de Privacidade periodicamente. Recomendamos revisar periodicamente as alterações. Seu uso contínuo do MealTracker após as alterações constitui aceitação dessas alterações.</p>

        <h5>Entre em Contato</h5>
        <p>Se tiver dúvidas sobre esta Política de Privacidade, entre em contato conosco em raulalves4@gmail.com.</p>

        <p>Obrigado por confiar no MealTracker para melhorar sua saúde e bem-estar!</p>
        <p>Última atualização: 18/09/2023</p>
      </div>
    </div>
  </div>
</div>

app/views/home/Services.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img3.webp"
                alt="login form" class="img-fluid" />
    </div>
    <div class="col-md-6">
      <div class="text-box">
        <h2>Serviços</h2>
        <p style="font-size: 18px;">Plano Freemium:</p>
        <ul style="font-size: 14px;">
          <li>Registre suas refeições diárias, incluindo detalhes como alimentos consumidos e porções.</li>
          <li>Acompanhe facilmente a quantidade de calorias consumidas em cada refeição e ao longo do dia.</li>
          <li>Registre suas atividades físicas, como caminhadas, corridas ou exercícios em academia.</li>
          <li>Obtenha gráficos simples e estatísticas básicas sobre sua ingestão de calorias e atividades físicas.</li>
          <li>Acesse uma seção de perguntas frequentes e um formulário de contato para obter suporte básico.</li>
        </ul>
        <p style="font-size: 18px;">Plano Premium:</p>
        <ul style="font-size: 14px;">
          <li>Receba recomendações personalizadas de dieta e exercícios com base nos seus dados.</li>
          <li>Monitore detalhadamente sua ingestão de calorias, incluindo contagem de macronutrientes.</li>
          <li>Tenha acesso a programas de treinamento físico personalizados, com exercícios e metas adequados às suas necessidades e objetivos.</li>
          <li>Acompanhe seu progresso ao longo do tempo com gráficos mais detalhados e estatísticas avançadas.</li>
          <li>Desfrute de suporte ao cliente prioritário, com tempos de resposta mais rápidos e assistência.</li>
        </ul>
    </div>
  </div>
</div>

app/views/home/_footer.html.erb
<footer class="footer">
  <div class="container-footer">
    <div class="row">
      <div class="footer-col">
        <h4>Empresa</h4>
        <ul>
         <li><%= link_to "Sobre" , home_about_path %></li>
         <li><%= link_to "Nossos Serviços" , home_Services_path %></li>
        </ul>
      </div>
      <div class="footer-col">
        <h4>Ajuda</h4>
        <ul>
          <li><%= link_to "Perguntas Frequentes" , home_FAQ_path %></li>
          <li><%= link_to "Opções de Pagamento" , home_Payment_path %></li>
      </div>
      <div class="footer-col">
        <h4>Siga-nos</h4>
        <div class="redes sociais">
          <a href="https://twitter.com/raulalves9" target="_blank"><i class="fab fa-twitter"></i></a>
          <a href="https://www.instagram.com/raulzamban/" target="_blank"><i class="fab fa-instagram"></i></a>
          <a href="https://www.linkedin.com/in/raul-alves-zamban-512b79112/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Sobre", home_about_path, class: "nav-link" %>
        </li>
      </ul>
      <!-- Right-aligned links -->
      <ul class="navbar-nav ml-auto">
        <!-- Always show Criar Conta link -->
        <li class="nav-item">
          <%= link_to "Criar conta", users_new_path, class: "nav-link" %>
        </li>
        <!-- Check if user is logged in -->
        <% if current_user %>
          <li class="nav-item">
           <%= link_to "Sair", sign_out_path, method: :delete, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Entrar", sign_in_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img2.webp"
                alt="login form" class="img-fluid" />
    </div>
    <div class="col-md-6">
      <div class="text-box">
        <h2>Sobre o Projeto</h2>
        <p>Esta página foi criada como parte de um pequeno projeto web em Ruby on Rails para a disciplina de Desenvolvimento Web. Este é o primeiro projeto em Rails do desenvolvedor, que está cursando Análise e Desenvolvimento de Sistemas no Senai Chapecó.</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- app/views/layouts/_footer.html.erb -->
<footer class="footer">
  <%= link_to "About", about_path %>
  <!-- More links -->
</footer>

app/views/layouts/_navbar.html.erb
<!-- app/views/layouts/_navbar.html.erb -->
<nav class="navbar">
  <%= link_to "Home", root_path %>
  <!-- More links -->
  <%= link_to "Account", edit_user_registration_path %>
</nav>

app/views/refeicos/edit.html.erb
<h1>Editando refeição</h1>

<%= render "form", refeico: @refeico %>

<br>

<div class="text-box">
  <%= link_to "Mostrar essa refeição", @refeico %> |
  <%= link_to "Voltar para refeições", refeicos_path %>
</div>

app/views/refeicos/index.html.erb
<p class="text-box" style="color: green"><%= notice %></p>

<h1>Refeições</h1>

<div class="text-box" id="refeicos">
  <% @refeicos.each do |refeico| %>
    <%= render refeico %>
    <p>
      <%= link_to "Mostrar essa refeição", refeico %>
    </p>
  <% end %>
</div>

<%= link_to "Nova refeição", new_refeico_path %>

app/views/refeicos/new.html.erb
<h1>Nova refeição</h1>

<br>

<%= render "form", refeico: @refeico %>
<div class="text-box">
  <%= link_to "Voltar para Refeições", refeicos_path %>

</div>

app/views/refeicos/show.html.erb
<p class="text-box"   style="color: green"><%= notice %></p>

<%= render @refeico %>

<div class="text-box">
  <%= link_to "Editar essa refeição", edit_refeico_path(@refeico) %> |
  <%= link_to "Voltar para refeições", refeicos_path %>

  <%= button_to "Deletar essa refeição", @refeico, method: :delete %>

  <%= link_to 'Voltar', dashboard_path %>
</div>

app/views/users/index.html.erb
<h1>Listando Usuários</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'Mostrar', user_path(user) %> |
          <%= link_to 'Editar', edit_user_path(user) %> |
          <%= link_to 'Destruir', user_path(user), method: :delete, data: { confirm: 'Você tem certeza?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Novo Usuário', new_user_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Voltar', users_path %>